<?php
/**
 * error_codes.inc.php
 * 
 * This file is where all error codes are defined.
 * All error code are named after the class and function they occur in.
 */

/**
 * Error number category defines.
 */
define( 'ARGUMENT_BASE_ERROR_NUMBER',   105000 );
define( 'DATABASE_BASE_ERROR_NUMBER',   205000 );
define( 'LDAP_BASE_ERROR_NUMBER',       305000 );
define( 'NOTICE_BASE_ERROR_NUMBER',     405000 );
define( 'PERMISSION_BASE_ERROR_NUMBER', 505000 );
define( 'RUNTIME_BASE_ERROR_NUMBER',    605000 );
define( 'SYSTEM_BASE_ERROR_NUMBER',     705000 );
define( 'TEMPLATE_BASE_ERROR_NUMBER',   805000 );
define( 'VOIP_BASE_ERROR_NUMBER',       905000 );

/**
 * "argument" error codes
 */
define( 'ARGUMENT_QUEUE__GET_QUERY_PARTS_ERROR_NUMBER',       ARGUMENT_BASE_ERROR_NUMBER + 1 );
define( 'ARGUMENT_SETTING_MANAGER____CONSTRUCT_ERROR_NUMBER', ARGUMENT_BASE_ERROR_NUMBER + 2 );
define( 'ARGUMENT_VOIP_CALL____CONSTRUCT_ERROR_NUMBER',       ARGUMENT_BASE_ERROR_NUMBER + 3 );
define( 'ARGUMENT_VOIP_MANAGER__CALL_ERROR_NUMBER',           ARGUMENT_BASE_ERROR_NUMBER + 4 );

/**
 * "database" error codes
 * 
 * Since database errors already have codes this list is likely to stay empty.
 */

/**
 * "ldap" error codes
 * 
 * Since ldap errors already have codes this list is likely to stay empty.
 */

/**
 * "notice" error codes
 */
define( 'NOTICE_ADDRESS_EDIT__FINISH_ERROR_NUMBER',             NOTICE_BASE_ERROR_NUMBER + 1 );
define( 'NOTICE_ADDRESS_NEW__FINISH_ERROR_NUMBER',              NOTICE_BASE_ERROR_NUMBER + 2 );
define( 'NOTICE_APPOINTMENT__SAVE_ERROR_NUMBER',                NOTICE_BASE_ERROR_NUMBER + 3 );
define( 'NOTICE_APPOINTMENT_EDIT__FINISH_ERROR_NUMBER',         NOTICE_BASE_ERROR_NUMBER + 4 );
define( 'NOTICE_APPOINTMENT_LIST____CONSTRUCT_ERROR_NUMBER',    NOTICE_BASE_ERROR_NUMBER + 5 );
define( 'NOTICE_APPOINTMENT_NEW__FINISH_ERROR_NUMBER',          NOTICE_BASE_ERROR_NUMBER + 6 );
define( 'NOTICE_ASSIGNMENT_BEGIN__FINISH_ERROR_NUMBER',         NOTICE_BASE_ERROR_NUMBER + 7 );
define( 'NOTICE_ASSIGNMENT_END__FINISH_ERROR_NUMBER',           NOTICE_BASE_ERROR_NUMBER + 8 );
define( 'NOTICE_CONSENT_NEW__FINISH_ERROR_NUMBER',              NOTICE_BASE_ERROR_NUMBER + 9 );
define( 'NOTICE_COVERAGE_EDIT____CONSTRUCT_ERROR_NUMBER',       NOTICE_BASE_ERROR_NUMBER + 10 );
define( 'NOTICE_COVERAGE_EDIT__FINISH_ERROR_NUMBER',            NOTICE_BASE_ERROR_NUMBER + 11 );
define( 'NOTICE_COVERAGE_NEW____CONSTRUCT_ERROR_NUMBER',        NOTICE_BASE_ERROR_NUMBER + 12 );
define( 'NOTICE_COVERAGE_NEW__FINISH_ERROR_NUMBER',             NOTICE_BASE_ERROR_NUMBER + 13 );
define( 'NOTICE_INTERVIEWER_ASSIGNMENT__FINISH_ERROR_NUMBER',   NOTICE_BASE_ERROR_NUMBER + 14 );
define( 'NOTICE_ONYX_INSTANCE_DELETE__FINISH_ERROR_NUMBER',     NOTICE_BASE_ERROR_NUMBER + 15 );
define( 'NOTICE_ONYX_INSTANCE_EDIT__FINISH_ERROR_NUMBER',       NOTICE_BASE_ERROR_NUMBER + 16 );
define( 'NOTICE_ONYX_INSTANCE_NEW__FINISH_ERROR_NUMBER',        NOTICE_BASE_ERROR_NUMBER + 17 );
define( 'NOTICE_PARTICIPANT_NEW__FINISH_ERROR_NUMBER',          NOTICE_BASE_ERROR_NUMBER + 18 );
define( 'NOTICE_PHONE_EDIT__FINISH_ERROR_NUMBER',               NOTICE_BASE_ERROR_NUMBER + 19 );
define( 'NOTICE_PHONE_NEW__FINISH_ERROR_NUMBER',                NOTICE_BASE_ERROR_NUMBER + 20 );
define( 'NOTICE_QNAIRE_NEW__FINISH_ERROR_NUMBER',               NOTICE_BASE_ERROR_NUMBER + 21 );
define( 'NOTICE_QUEUE_RESTRICTION_DELETE__FINISH_ERROR_NUMBER', NOTICE_BASE_ERROR_NUMBER + 22 );
define( 'NOTICE_QUEUE_RESTRICTION_EDIT__FINISH_ERROR_NUMBER',   NOTICE_BASE_ERROR_NUMBER + 23 );
define( 'NOTICE_QUEUE_RESTRICTION_NEW__FINISH_ERROR_NUMBER',    NOTICE_BASE_ERROR_NUMBER + 24 );
define( 'NOTICE_SITE_EDIT__FINISH_ERROR_NUMBER',                NOTICE_BASE_ERROR_NUMBER + 25 );
define( 'NOTICE_SITE_NEW__FINISH_ERROR_NUMBER',                 NOTICE_BASE_ERROR_NUMBER + 26 );
define( 'NOTICE_VOIP_MANAGER__CALL_ERROR_NUMBER',               NOTICE_BASE_ERROR_NUMBER + 27 );

/**
 * "permission" error codes
 */

/**
 * "runtime" error codes
 */
define( 'RUNTIME_ADDRESS_ADD__FINISH_ERROR_NUMBER',              RUNTIME_BASE_ERROR_NUMBER + 1 );
define( 'RUNTIME_APPOINTMENT__VALIDATE_DATE_ERROR_NUMBER',       RUNTIME_BASE_ERROR_NUMBER + 2 );
define( 'RUNTIME_APPOINTMENT_ADD__FINISH_ERROR_NUMBER',          RUNTIME_BASE_ERROR_NUMBER + 3 );
define( 'RUNTIME_APPOINTMENT_LIST__FINISH_ERROR_NUMBER',         RUNTIME_BASE_ERROR_NUMBER + 4 );
define( 'RUNTIME_AVAILABILITY_ADD__FINISH_ERROR_NUMBER',         RUNTIME_BASE_ERROR_NUMBER + 5 );
define( 'RUNTIME_CONSENT_ADD__FINISH_ERROR_NUMBER',              RUNTIME_BASE_ERROR_NUMBER + 6 );
define( 'RUNTIME_LDAP_MANAGER__SET_USER_PASSWORD_ERROR_NUMBER',  RUNTIME_BASE_ERROR_NUMBER + 7 );
define( 'RUNTIME_PARTICIPANT_PRIMARY____CONSTRUCT_ERROR_NUMBER', RUNTIME_BASE_ERROR_NUMBER + 8 );
define( 'RUNTIME_PARTICIPANT_WITHDRAW__FINISH_ERROR_NUMBER',     RUNTIME_BASE_ERROR_NUMBER + 9 );
define( 'RUNTIME_PHASE_ADD__FINISH_ERROR_NUMBER',                RUNTIME_BASE_ERROR_NUMBER + 10 );
define( 'RUNTIME_PHONE_ADD__FINISH_ERROR_NUMBER',                RUNTIME_BASE_ERROR_NUMBER + 11 );
define( 'RUNTIME_PHONE_CALL_BEGIN__FINISH_ERROR_NUMBER',         RUNTIME_BASE_ERROR_NUMBER + 12 );
define( 'RUNTIME_RECORD____CALL_ERROR_NUMBER',                   RUNTIME_BASE_ERROR_NUMBER + 13 );
define( 'RUNTIME_SESSION__GET_CURRENT_ASSIGNMENT_ERROR_NUMBER',  RUNTIME_BASE_ERROR_NUMBER + 14 );
define( 'RUNTIME_SESSION__GET_CURRENT_PHONE_CALL_ERROR_NUMBER',  RUNTIME_BASE_ERROR_NUMBER + 15 );
define( 'RUNTIME_SID_RECORD__GET_TABLE_NAME_ERROR_NUMBER',       RUNTIME_BASE_ERROR_NUMBER + 16 );
define( 'RUNTIME_SURVEY_TIMINGS__GET_TABLE_NAME_ERROR_NUMBER',   RUNTIME_BASE_ERROR_NUMBER + 17 );
define( 'RUNTIME_VOIP_MANAGER__INITIALIZE_ERROR_NUMBER',         RUNTIME_BASE_ERROR_NUMBER + 18 );
define( 'RUNTIME_VOIP_MANAGER__CALL_ERROR_NUMBER',               RUNTIME_BASE_ERROR_NUMBER + 19 );

/**
 * "system" error codes
 * 
 * Since system errors already have codes this list is likely to stay empty.
 * Note the following PHP error codes:
 *      1: error,
 *      2: warning,
 *      4: parse,
 *      8: notice,
 *     16: core error,
 *     32: core warning,
 *     64: compile error,
 *    128: compile warning,
 *    256: user error,
 *    512: user warning,
 *   1024: user notice
 */

/**
 * "template" error codes
 * 
 * Since template errors already have codes this list is likely to stay empty.
 */

/**
 * "voip" error codes
 */
define( 'VOIP_VOIP_CALL__DTMF_ERROR_NUMBER',                 VOIP_BASE_ERROR_NUMBER + 1 );
define( 'VOIP_VOIP_CALL__PLAY_SOUND_ERROR_NUMBER',           VOIP_BASE_ERROR_NUMBER + 2 );
define( 'VOIP_VOIP_CALL__START_MONITORING_ERROR_NUMBER',     VOIP_BASE_ERROR_NUMBER + 3 );
define( 'VOIP_VOIP_CALL__STOP_MONITORING_ERROR_NUMBER',      VOIP_BASE_ERROR_NUMBER + 4 );
define( 'VOIP_VOIP_MANAGER__INITIALIZE_ERROR_NUMBER',        VOIP_BASE_ERROR_NUMBER + 5 );
define( 'VOIP_VOIP_MANAGER__REBUILD_CALL_LIST_ERROR_NUMBER', VOIP_BASE_ERROR_NUMBER + 6 );
define( 'VOIP_VOIP_MANAGER__CALL_ERROR_NUMBER',              VOIP_BASE_ERROR_NUMBER + 7 );

?>
